### ISSUE TITLE
Data table address search not working for ditch service area

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#390] opened 2021-04-28 20:44 UTC
For the Poudre Basin Information website, I displayed ***Basin Entities / Agriculture - Ditches***.  Then I used the data table to search for the office address, which should return a match but did not.  What is going on?  Is the intersect algorithm robust for the polygon data?

**Comment by Nightsphere** [comment] 2021-06-15 21:40
I believe this was a single symbol/categorized/graduated problem, and was fixed as part of another issue. it is currently working as intended. Closing this issue.

**Closed by Nightsphere** 2021-06-15 21:40 UTC
Labels: XS, bug, high
