### ISSUE TITLE
Need a way to configure favicon

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#141] opened 2020-06-08 04:52 UTC
**This needs to be resolved for the `cdss-app-statemod-web` project.**

Need a way to specify the favicon for the application to brand the application.

Worst case, need documentation to know how to overwrite the favicon that is packaged with the application and might need to overwrite a file when deployed.

Ideally can added as a top-level configuration property in the application configuration file, for example `favicon` property.

Maybe this is a small research task that Sofia can work on.

**Comment by Nightsphere** [comment] 2020-06-16 21:17
There is a way to dynamically use the favicon in the app, so I have created a new app-configuration
property called `favicon` which will hold the path to the user's file they would like as the favicon.
This can take either an absolute or relative path. For example:

`favicon: "/img/OWF-Logo-Favicon-32x32.ico"` or
`favicon: "img/OWF-Logo-Favicon-32x32.ico"`

By default, if no favicon property is given, the OWF Logo will be shown. Maybe I won't close this
issue until we get the favicon property into the documentation?

**Comment by smalers** [comment] 2020-06-17 04:31
I added the property to the documentation. My current test environment for the Poudre currently does not show this feature working but I understand the next push will work.  Verify the feature then and keep open for now.  I suggest changing the default filename to all lowercase.

**Comment by Nightsphere** [comment] 2020-06-17 20:24
The new favicon push is up and hopefully has fixed the issue it was having previously.

**Comment by smalers** [comment] 2020-06-18 04:59
The Poudre application favicon is now showing up locally or on Amazon.  Here are the resources that are used:

* [app-config.json](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/blob/master/web/app-config.json)
* [image file](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/blob/master/web/img/owf-logo-favicon-32x32.ico)

The icon file was copied from the default app.  I viewed it in Gimp and it looks OK.

**Comment by smalers** [comment] 2020-06-19 04:23
There seems to be an issue where if the application favicon file matches the name of the default favicon file (matching case or otherwise), then no favicon is used.  I changed the name to not be in conflict and it works.  Keep this open and try to figure out if there is a subtle issue that needs to be resolved.

**Comment by Nightsphere** [comment] 2022-02-17 22:04
This was a tiny fix that I tacked on to another issue months ago, and is now working as intended. Closing this issue.

**Closed by Nightsphere** 2022-02-17 22:04 UTC
Labels: enhancement, high, S
