### ISSUE TITLE
Showdown CSS for bullets is wrong?

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#387] opened 2021-04-28 05:42 UTC
The CSS for top level bullets for markdown/showdown seems wrong.  It is showing in bold when it should be normal font?  If the author wants bold they can define that themselves.  I don't know if there are other formatting things that should be changed.

**Comment by Nightsphere** [comment] 2022-03-02 22:05
I believe this was fixed months ago, and I cannot recreate. It can be opened up again if the problem is found again. Closing the issue.

**Closed by Nightsphere** 2022-03-02 22:05 UTC
Labels: bug, high, XS
